12_Python_Lecture/Django/01_django_orm/crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

12_Python_Lecture/Django/01_django_orm/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

12_Python_Lecture/Django/01_django_orm/crud/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True) 
    #auto_now_add = 최초 생성 일자
    updated_at = models.DateTimeField(auto_now=True)
    users = models.TextField(default='test')

12_Python_Lecture/Django/01_django_orm/crud/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles,
    }
    
    return render(request, 'articles/index.html', context)


def new(request):
    return render(request, 'articles/new.html')


def create(request):
    # 1. new에서 보낸 데이터 받기
    title = request.POST.get('title')
    content = request.POST.get('content')

    # 2. DB에 저장
    # (2) 인스턴스 사용
    article = Article(title=title, content=content)
    # 데이터가 유효한지 검사
    article.save()

    # 3. context에 보내주기
    return redirect('articles:detail', article.pk)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article,
    }
    return render(request, 'articles/detail.html', context)


def delete(request, pk):
    print(request.method)
    article = Article.objects.get(pk=pk)
    if request.method == 'POST' : 
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)
    


def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article,
    }

    return render(request, 'articles/edit.html', context)


    # article.title = request.POST.get('title')
    # article.content = request.POST.get('content')
    # article.save()

    # return redirect('articles:index')


def update(request, pk):
    # 1. 수정할 게시글 조회
    article = Article.objects.get(pk=pk)
    # title = request.POST.get('title')
    # content = request.POST.get('content')

    # 2. edit 에서 보낸 이미지를 받아서 기존값을 받기
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()

    return redirect('articles:detail', article.pk)

12_Python_Lecture/Django/01_django_orm/crud/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create</h1>
    <h2>성공적으로 작동</h2>  
    <table>
        <tr>
            <th>PK</th>
            <th>Ttitle</th>
            <th>Content</th>
            <th>Created_at</th>
            <th>Updated_at</th>
        </tr>
        <tr>
            {% for article in articles %}
                <td> {{ article.pk }}</td>
                <td> {{ article.title }}</td>
                <td> {{ article.content }}</td>
                <td> {{ article.created_at }}</td>
                <td> {{ article.updated_at }}</td>
            {% endfor %}
        </tr>
    </table>
{% endblock  %}

12_Python_Lecture/Django/01_django_orm/crud/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>DETAIL</h1>
    <h2>{{ article.pk }}번 문서 입니다.</h2>
    <table style="width:100%;">
        <tr>
            <th>ID</th>
            <th>제목</th>
            <th>내용</th>
            <th>작성시간</th>
            <th>수정시간</th>
        </tr>
        <tr>
            <td>{{ article.pk }}</td>
            <td>{{ article.title }}</td>
            <td>{{ article.content }}</td>
            <td>{{ article.created_at }}</td>
            <td>{{ article.updated_at }}</td>
        </tr>
    </table>
    <hr>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-warning">삭제하기</button>
    </form>

    <a href="{% url 'articles:edit' article.pk %}"><button type="button" class="btn btn-primary">수정하기</button></a>
    <!--<a href="{% url 'articles:delete' article.pk%}">delete</a>-->
    <a href="{% url 'articles:index' %}"><button class="btn btn-info">처음으로</button></a>
{% endblock  %}

12_Python_Lecture/Django/01_django_orm/crud/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>EDIT</h1>
    <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
        <input type="text" name="title" value="{{ article.title }}"><br>
        <textarea type="text" name="content">{{ article.content }}</textarea><br><!-- textarea에는 value속성이 없음! 주의해서 사용하기-->
        <button class="btn-primary">수정</button>
    </form>
    <a href="{% url 'articles:index' %}">just go back</a>
{% endblock  %}

12_Python_Lecture/Django/01_django_orm/crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">성공</h1>
    <a href="{% url 'articles:new' %}">NEW</a>
    <hr>
    <table style="width:100%;">
        <tr>
            <th>글 번호</th>
            <th>글 제목</th>
            <th>글 내용</th>
            <th>updated_at</th>
            <th>back?</th>
        </tr>
        {% for article in articles %}
        <tr>
            <td>{{ article.pk}}</td>
            <td>{{ article.title}}</td>
            <td>{{ article.content}}</td>
            <td>{{ article.updated_at }}
            <td><a href="{% url 'articles:detail' article.pk %}"><button type="button" class="btn btn-primary">see details</button> </a></td>
        </tr>
        {% endfor %}
    </table>
     
{% endblock  %}

12_Python_Lecture/Django/01_django_orm/crud/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
    <h1>NEW</h1>
    <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
        <input type="text" name="title"><br>
        <textarea type="text" name="content"></textarea><br>
        <button class="btn-primary">send</button>
    </form>
{% endblock  %}