12_Python_Lecture/Django/06_insta/insta/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    # 
]

12_Python_Lecture/Django/06_insta/insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
# media를 위해서
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    
]

# media url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

12_Python_Lecture/Django/06_insta/insta/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/like/', views.like, name='like'),
]

12_Python_Lecture/Django/06_insta/insta/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


class User(AbstractUser):
    following = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='follower')
    # 이 유저가 갖고 있는 사람들 
    image = ProcessedImageField(
        upload_to='profile_image',
        processors=[ResizeToFill(500, 500)],
        format='JPEG',
        options={
            'quality': 60},
        default='default.png')
    # user_set이 새로 칼럼 생성되서 이름을 follower로 변화
    

12_Python_Lecture/Django/06_insta/insta/posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit


# post_set = FK => (어떤 유저가 작성한 글들)
# post_set = M2M => (어떤 유저가 좋아요 버튼을 누른 글들)
# related_name을 통해서 like_posts로 바꿔서 
# 두개의 이름이 똑가아서 충돌
 
class Post(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    # image = models.ImageField()
    image = ProcessedImageField(
        processors=[ResizeToFit(500, 500)],
        format='JPEG',
        options={
            'quality': 60})
            

    # user.like_posts -> 이 유저가 좋아유를 누른 "포스트들" posts liked by user 
    # post.like_users -> 이 포스트를 좋아하는 "유저들"     users who like the posts

    # user = 작성한 사람을 저장하기 위한
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # 좋아요를 누른 사람을 가져올 콜롬을 만들기
    # like_user = 좋아요 버튼을 누른사람들을 저장
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

    class Meta:
        ordering = ['-id']

12_Python_Lecture/Django/06_insta/insta/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.contrib.auth import get_user_model
# get_user_model => AUTH_USER_MODEL에 적용시킨 모델 클래스

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'image')

12_Python_Lecture/Django/06_insta/insta/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        #fields = '__all__'
        exclude = ('user', 'like_users',)

12_Python_Lecture/Django/06_insta/insta/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
        
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('posts:index')

    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('accounts:login')


def profile(request, username):
    # User = get_user_model()
    # user_profile = User.objects.get(username=username)

    # 왜 post에서 아니고 user에서 가져오나...?
    user_profile =  get_object_or_404(get_user_model() , username=username)
    context = {
        'user_profile' : user_profile,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    me = request.user
    you = get_object_or_404(get_user_model(), pk=user_pk)


    if me == you:
        return redirect('posts:index')


    if me in you.follower.all():
    # if you in me.following.all():
        # 이미 팔로우 하고 있었음
        you.follower.remove(me)
        # me.following.remove(you)
    else:
        # 아직 팔로우 안함
        you.follower.add(me)
        # me.following.add(you)

    return redirect('accounts:profile', you.username)

12_Python_Lecture/Django/06_insta/insta/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from .models import Post
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required 
from django.http import JsonResponse


def index(request):
    posts = Post.objects.all()
    context = {
        'posts' : posts,
    }
    return render(request, 'posts/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form =PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()

    context = {
        'form' : form,
    }
    return render(request, 'posts/form.html', context)


@login_required
def like(request, post_pk):
    user = request.user
    post = get_object_or_404(Post, pk=post_pk)

    # if 좋아요 버튼을 아직 안누른 경우:
    #     pass
    #  else  이미 누른 경우:
    #     pass

    # user.like_posts => user가 좋아요 버튼을 누른 게시물들
    # post.like_users => post에 좋아요 버튼을 누른 유저들

    if post in user.like_posts.all():
        # 좋아요 버튼을 이미 누른 게시물들
        user.like_posts.remove(post)
        liked = False
    else:
        # 좋아요 버튼을 아직 안누른 게시물들
        user.like_posts.add(post)
        liked = True


    context = {
        'msg' : '좋아요기능이 동작했',
        'liked' : liked,
    }
    # return redirect('posts:index')
    return JsonResponse(context)

12_Python_Lecture/Django/06_insta/insta/posts/templates/posts/card.html
  <div class="card">
    <div class="m-2">
      <h5 class="card-header">
        <img class="rounded-circle" src="https://scontent-gmp1-1.cdninstagram.com/v/t51.2885-19/s150x150/104372084_1934600830007823_5517973791797721718_n.jpg?_nc_ht=scontent-gmp1-1.cdninstagram.com&_nc_ohc=0SJIb-T4I9gAX_67mB6&oh=0b2038b5639b8484acf398e2dad26eea&oe=5F1DDAC2" width='30px' height='30px'>
        <a href="{% url 'accounts:profile' post.user.username %}">{{ post.user.username }}</a>
      </h5>
      <img src="{{ post.image.url }}" class="card-img-top">
      {% if post in user.like_posts.all %}
        <!-- 원래 a태그로 감싸져있는데, 이제 ajax로 액션 만들기 -->
        <i data-id="{{ post.id }}" class="fas fa-heart fa-lg" style="color:red"></i>
      {% else %}
        <i data-id="{{ post.id }}" class="far fa-heart fa-lg" style="color:black"></i>
      {% endif %}
        <div class="card-body">
          <p class="card-title">{{ post.content }}</p>
          <p class="card-text">{{ post.created_at }}</p>
          <p>{{ post.image.url }}</p><!-- image의 url을 가져온다는 뜻!?!?!-->
        </div>
    </div>
  </div>

 {% comment %} <a href="{% url 'posts:like' post.pk %}"> {% endcomment %}
 

12_Python_Lecture/Django/06_insta/insta/posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btsn-success">저장</button>
    </form>
{% endblock  %}

12_Python_Lecture/Django/06_insta/insta/posts/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="row row-cols-3">
    {% for post in posts %}
      {% include 'posts/card.html' %}
    {% endfor %}
  </div>
  <!--card script-->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
  // 1. A를
  var likeButtons = document.querySelectorAll('.fa-heart')
  //console.log(likeButtons)

  // likeButtons.forEach(()=>{})
  likeButtons.forEach(function(likeButton){
    //console.log(likeButton)
    // === for likeButton in likeButtons

    // 2. B 했을 때
    likeButton.addEventListener('click', function(event){
      //console.log(event.target.dataset.id)
      //data-id 이기 때뭉네 dataset.하고서 +id로 적은 거다!
      var targetId = event.target.dataset.id
      axios.get(`/posts/${targetId}/like/`)
      .then(function(response){
        console.log(response.data.liked) //아직까지는 html을 response중.
        //True 혹은 False
        if (response.data.liked){
          //True이면 좋아요를 누른 경우
          event.target.style.color = 'red'
          event.target.classList.remove('far')
          event.target.classList.add('fas')
        }
        else{
          //True이면 좋아요를 취소하는 경우
          event.target.style.color = 'black'
          event.target.classList.remove('fas')
          event.target.classList.add('far')
        }
      })
      //.then().catch()
      // ` is not single quoatation martk

    })
    // 안의 인자에다가 뭐를 기다렸다가 뭐를 해줘
  })
  // 3. C를 한다.
  </script>
  
{% endblock %}