12_Python_Lecture/Django/04_django_auth/crud/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

12_Python_Lecture/Django/04_django_auth/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('todos/', include('todos.urls')),
]

12_Python_Lecture/Django/04_django_auth/crud/todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

12_Python_Lecture/Django/04_django_auth/crud/accounts/models.py
from django.db import models

# Create your models here.

12_Python_Lecture/Django/04_django_auth/crud/todos/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Todo(models.Model):
    content = models.CharField(max_length=100)
    due_date = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user 에는 number
    # User을 만들지 않았다. 그래서 어디선가 가져와야한다.
    # 뭐쓸지 말해주는 변수를 쓰면 나중에 뒤에 들어간느 이름이 바껴도 변수를 바꿀 필요가 없다.

12_Python_Lecture/Django/04_django_auth/crud/todos/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    content = forms.CharField(
        widget = forms.TextInput(
            attrs = ({
                'class' : 'my-content form-control',
                'placeholder' : 'Enter the content:',
            })
        )
    )
    due_date = forms.CharField(
        widget = forms.TextInput(
            attrs = ({
                'class' : 'my-due_date form-control',
                'type' : 'date',
            })
        )
    )
    class Meta:
        model = Todo
        fields = ('content', 'due_date')
        # exclude = ('user',)

12_Python_Lecture/Django/04_django_auth/crud/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save() # model에 save가 맞다.
            return redirect('accounts:login')
    else:
        form = UserCreationForm()

    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.method == 'POST':
        # 구조가 UserCreationForm하고는 다르다.
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            # form.save()가 아니다. / login 함수를 갖다 쓰면된다.
            auth_login(request, form.get_user())
            # login 함수는 -> login(1번째이자-request, 2번째인자-user)
            return redirect('todos:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

12_Python_Lecture/Django/04_django_auth/crud/todos/views.py
from django.shortcuts import render, redirect
from .forms import TodoForm
from .models import Todo
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required
def index(request):
    # index에서 입력받으니깐
    form = TodoForm()
    #todos = Todo.objects.all()
    context = {
        'form' : form,
        #'todos' : todos,
    }
    return render(request, 'todos/index.html', context)


@login_required
def create(request):
    form = TodoForm(request.POST)
    if form.is_valid():
        # User 정보를 지금 가져올 수는 없다. 
        # 로그인한 사용자의 정보를 가져오는 것이 필요
        todo = form.save(commit=False)
        # User 정보를 가져와야지
        todo.user = request.user
        todo.save()
        return redirect('todos:index')


def delete(request, pk):
    todo = Todo.objects.get(pk=pk)
    todo.delete()
    return redirect('todos:index')


    
    

12_Python_Lecture/Django/04_django_auth/crud/todos/templates/todos/index.html
{% extends 'base.html' %}


{% block top %}<h1 class="text-center mt-5">Todo List</h1>{% endblock  %}
  {% block body %}  
    <form action="{% url 'todos:create' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <button class="d-inline btn btn-primary">저장</button>
    </form>
    <hr>
    <div class="row">
        {% for todo in user.todo_set.all %}
            <div class="col-8">
                {% if todo %}
                    <p>{{ todo.content }}</p>
                {% else %}
                    <p>{{ todo.content }}</p>
                {% endif %}
            </div>

            <div class="col-2">
                <p>{{ todo.due_date }}</p>
            </div>
            <div class="col-2">
                <form action="{% url 'todos:delete' todo.pk %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger">삭제하기</button>
                </form>
            </div>
            <hr>
        {% endfor %}
    </div> 
{% endblock  %}